export const DISPLAY_ALERT = "SHOW_ALERT";

export const CLEAR_ALERT = "CLEAR_ALERT";
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = " REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = " REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = " LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = " LOGIN_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_POST_BEGIN = "CREATE_POST_BEGIN";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const GET_POST_BEGIN = "GET_POST_BEGIN";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";

export const GET_SINGLE_POST_BEGIN = "GET_SINGLE_POST_BEGIN";
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS";
export const GET_SINGLE_POST_ERROR = " GET_SINGLE_POST_ERROR";

export const SET_EDIT_POST = "SET_EDIT_POST";

export const SET_POST_ID = "SET_POST_ID";

export const DELETE_POST_BEGIN = "DELETE_POST_BEGIN";

export const EDIT_POST_BEGIN = "EDIT_POST_BEGIN";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_ERROR = "EDIT_POST_ERROR";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const CREATE_HEALTH_POST_BEGIN = "CREATE_HEALTH_POST_BEGIN";
export const CREATE_HEALTH_POST_SUCCESS = "CREATE_HEALTH_POST_SUCCESS";
export const CREATE_HEALTH_POST_ERROR = "CREATE_HEALTH_POST_ERROR";

export const GET_HEALTH_POST_BEGIN = "GET_HEALTH_POST_BEGIN";
export const GET_HEALTH_POST_SUCCESS = "GET_HEALTH_POST_SUCCESS";

export const SET_EDIT_HEALTH_POST = "SET_EDIT_HEALTH_POST";

export const DELETE_HEALTH_POST_BEGIN = "DELETE_HEALTH_POST_BEGIN";

export const EDIT_HEALTH_POST_BEGIN = "EDIT_HEALTH_POST_BEGIN";
export const EDIT_HEALTH_POST_SUCCESS = "EDIT_HEALTH_POST_SUCCESS";
export const EDIT_HEALTH_POST_ERROR = "EDIT_HEALTH_POST_ERROR";

export const CREATE_EVENT_BEGIN = "CREATE_EVENT_BEGIN";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_ERROR = "CREATE_EVENT_ERROR";

export const GET_EVENTS_BEGIN = "GET_EVENTS_BEGIN";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";

export const SET_EDIT_EVENT = "SET_EDIT_EVENT";

export const DELETE_EVENT_BEGIN = "DELETE_EVENT_BEGIN";

export const EDIT_EVENT_BEGIN = "EDIT_EVENT_BEGIN";
export const EDIT_EVENT_SUCCESS = "EDIT_EVENT_SUCCESS";
export const EDIT_EVENT_ERROR = "EDIT_EVENT_ERROR";

export const CREATE_REQUEST_BEGIN = "CREATE_REQUEST_BEGIN";
export const CREATE_REQUEST_SUCCESS = "CREATE_REQUEST_SUCCESS";
export const CREATE_REQUEST_ERROR = "CREATE_REQUEST_ERROR";

export const GET_REQUEST_BEGIN = "GET_REQUEST_BEGIN";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";

export const DELETE_REQUEST_BEGIN = "DELETE_REQUEST_BEGIN";

export const GET_PHOTOS_BEGIN = "GET_PHOTOS_BEGIN";
export const GET_PHOTOS_SUCCESS = "GET_PHOTOS_SUCCESS";

export const CREATE_PDF_BEGIN = "CREATE_PDF_BEGIN";
export const CREATE_PDF_SUCCESS = "CREATE_PDF_SUCCESS";
export const CREATE_PDF_ERROR = "CREATE_PDF_ERROR";

export const UPLOAD_IMAGE_BEGIN = "UPLOAD_IMAGE_BEGIN";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR";

export const CREATE_PASTOR_BEGIN = "CREATE_PASTOR_BEGIN";
export const CREATE_PASTOR_SUCCESS = "CREATE_PASTOR_SUCCESS";
export const CREATE_PASTOR_ERROR = "CREATE_PASTOR_ERROR";

export const CREATE_WORKER_BEGIN = "CREATE_WORKER_BEGIN";
export const CREATE_WORKER_SUCCESS = "CREATE_WORKER_SUCCESS";
export const CREATE_WORKER_ERROR = "CREATE_WORKER_ERROR";

export const CREATE_POSITION_BEGIN = "CREATE_POSITION_BEGIN";
export const CREATE_POSITION_SUCCESS = "CREATE_POSITION_SUCCESS";
export const CREATE_POSITION_ERROR = "CREATE_POSITION_ERROR";

export const GET_POSITION_BEGIN = "GET_POSITION_BEGIN";
export const GET_POSITION_SUCCESS = "GET_POSITION_SUCCESS";

export const GET_PASTOR_BEGIN = "GET_PASTOR_BEGIN";
export const GET_PASTOR_SUCCESS = "GET_PASTOR_SUCCESS";

export const GET_WORKER_BEGIN = "GET_WORKER_BEGIN";
export const GET_WORKER_SUCCESS = "GET_WORKER_SUCCESS";

export const CREATE_ELDER_BEGIN = "CREATE_ELDER_BEGIN";
export const CREATE_ELDER_SUCCESS = "CREATE_ELDER_SUCCESS";
export const CREATE_ELDER_ERROR = "CREATE_ELDER_ERROR";

export const GET_ELDER_BEGIN = "GET_ELDER_BEGIN";
export const GET_ELDER_SUCCESS = "GET_ELDER_SUCCESS";

export const CREATE_REVIEW_BEGIN = "CREATE_REVIEW_BEGIN";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_ERROR = "CREATE_REVIEW_ERROR";

export const GET_REVIEW_BEGIN = "GET_REVIEW_BEGIN";
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";

export const CREATE_RESOURCE_BEGIN = "CREATE_RESOURCE_BEGIN";
export const CREATE_RESOURCE_SUCCESS = "CREATE_RESOURCE_SUCCESS";
export const CREATE_RESOURCE_ERROR = "CREATE_RESOURCE_ERROR";

export const GET_RESOURCE_BEGIN = "GET_RESOURCE_BEGIN";
export const GET_RESOURCE_SUCCESS = "GET_RESOURCE_SUCCESS";
